In [11]:
import os

os.environ["KMP_DUPLICATE_LIB_OK"]="TRUE"
import numpy as np
import torch
import math 
import copy
import random
import argparse
import torch.optim as optim
import modeldefine 

In [20]:
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

In [19]:
inputs

tensor([[-8.8680e-01, -1.2096e+00,  1.4764e+00, -4.0708e-03,  2.9090e-01,
         -4.0821e-01,  8.9770e-01,  9.7467e-02,  2.3289e-01,  2.0431e-01,
         -1.8806e+00, -2.1778e+00,  1.9013e+00,  8.6445e-02, -1.4812e-02,
          1.1121e+00,  1.1734e+00,  1.2907e+00, -1.2793e+00,  4.9042e-01],
        [-4.8368e-01,  3.5028e-01,  1.5262e+00, -6.9248e-01,  7.9303e-01,
          3.2805e-01,  1.0426e+00,  1.0812e-01,  1.3142e+00, -6.6606e-01,
          4.0916e-01,  2.9042e-01, -1.3784e+00,  5.2501e-01,  7.3356e-01,
          1.6090e+00,  4.4904e-01, -7.6869e-01, -1.4498e-01, -8.4818e-01],
        [-1.5003e+00, -7.1569e-01, -3.5727e-01,  7.9575e-01,  6.0341e-01,
          2.5709e-01,  3.9753e-01, -1.3197e+00,  2.5282e+00,  1.2057e+00,
         -1.0181e+00, -4.5934e-01, -1.3599e+00, -2.1718e-01, -6.6340e-01,
          1.3251e+00, -7.0353e-01,  1.1073e+00, -9.6174e-01,  7.8982e-01],
        [-3.2329e-01,  2.9460e-01,  1.8908e+00,  1.4062e+00, -4.0951e-01,
         -1.3820e+00, -1.1750e-02, 

In [30]:

import torch.nn as nn

model = modeldefine.Model(15,20,15,5).to(device)
# 定义自定义的MSE损失
class CustomMSELoss(nn.Module):
    def __init__(self, theta):
        super(CustomMSELoss, self).__init__()
        self.theta = theta
        self.mse_loss = nn.MSELoss()

    def forward(self, output, target):
        prediction = torch.sum(output * self.theta, dim=1)  # 按元素乘法并求和
        return self.mse_loss(prediction, target)

# 示例用法
batch_size = 32
input_dim = 30

output_dim = 15 # 假设神经网络的输出是10维的

# 随机数据和theta
inputs = torch.randn(batch_size, input_dim).to(device)
theta_values = torch.randn(batch_size, output_dim).to(device)
targets = torch.randn(batch_size).to(device)


# 创建模型、损失函数和优化器

loss_function = CustomMSELoss(theta_values)
optimizer = optim.Adam(model.parameters(), lr=0.01)  # 仅优化神经网络的参数

# ... (其他代码，如模型、损失函数和优化器的定义等)

epochs = 10
for epoch in range(epochs):
    # 前向传播
    outputs = model(inputs)
    loss = loss_function(outputs, targets)
    
    # 打印损失
    print(f"Epoch [{epoch+1}/{epochs}], Loss: {loss.item()}")

    # 反向传播和优化
    optimizer.zero_grad()  # 重要：每次迭代前清零梯度
    loss.backward()
    optimizer.step()

tensor([15, 20, 20, 20, 20, 20, 15], dtype=torch.int32)
Epoch [1/10], Loss: 32.90570068359375
Epoch [2/10], Loss: 16.577245712280273
Epoch [3/10], Loss: 2.4929914474487305
Epoch [4/10], Loss: 1.0661158561706543
Epoch [5/10], Loss: 0.7045682668685913
Epoch [6/10], Loss: 1.2495797872543335
Epoch [7/10], Loss: 0.6601899862289429
Epoch [8/10], Loss: 0.6595432758331299
Epoch [9/10], Loss: 0.6966903209686279
Epoch [10/10], Loss: 0.6644837856292725


In [24]:
inputs

tensor([[-1.3595e+00, -8.4486e-01,  2.9120e-01, -1.1012e+00, -4.9451e-01,
          5.7565e-01, -3.6274e-01, -1.1452e+00, -2.3266e-01, -2.1002e+00,
          6.2505e-01, -3.8210e-01,  7.0174e-01,  5.7446e-02,  1.1780e+00,
          1.8395e-01, -5.3877e-01,  6.8563e-01,  5.0149e-01,  1.5806e+00,
         -6.9712e-01, -4.7698e-01,  6.5978e-01, -1.0632e+00,  7.6675e-01,
          9.5714e-01,  1.7063e-01,  2.6369e-01,  1.1777e+00, -7.3357e-01],
        [-7.7922e-01,  1.2000e+00, -8.3721e-02, -1.6385e+00, -1.6120e+00,
          5.4735e-01, -2.3277e-01, -6.1234e-02, -1.4840e+00, -1.9476e+00,
         -1.0582e+00,  7.1696e-01,  9.2314e-01, -1.6217e-01,  3.2166e-01,
          3.8077e-01, -1.0759e+00, -2.4567e-02,  8.3509e-01, -4.9085e-01,
         -1.3277e+00, -1.3632e+00, -8.5858e-01, -8.8026e-01,  5.6584e-01,
          1.0450e+00,  6.2122e-01, -7.6307e-01,  4.6558e-01,  7.1737e-02],
        [-3.9139e-01,  4.9584e-01, -7.9030e-02, -3.8381e-01, -3.9957e-01,
         -2.6767e-01,  9.5374e-01,  

In [25]:
outputs

tensor([[0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.

In [26]:
targets

tensor([ 0.3253,  0.1033,  0.3370, -1.9667, -0.9502,  1.9022,  1.6008,  0.2493,
        -0.2534, -0.2236,  0.2426, -1.7176,  0.3083, -0.2680, -0.5964,  0.2690,
        -0.1119,  1.4921,  0.2294,  1.0837,  0.0157,  1.1850,  0.2684,  1.0742,
        -1.3413, -2.0610, -0.7537, -0.4958, -0.0071,  0.4423,  0.8250, -0.3918],
       device='cuda:0')

In [28]:
theta_values

tensor([[-2.5613e+00,  8.5988e-01, -1.3511e+00,  4.9824e-01,  2.8846e-01,
         -1.1146e+00,  1.9008e+00,  1.9717e+00, -1.9164e+00,  9.5758e-01,
          1.6741e+00, -1.1374e+00, -1.0036e+00,  3.3130e-01, -2.2969e-01],
        [-2.4799e-01,  1.2666e+00, -4.0837e-01, -3.0024e-01,  1.2016e+00,
         -1.2343e+00,  7.1865e-01,  5.7791e-02,  1.4830e-01,  2.5844e-01,
          2.5967e-01, -1.4547e-01,  9.6501e-02, -1.1068e+00,  1.3168e+00],
        [ 1.2348e-01, -1.0810e+00, -1.4468e-01, -2.4823e-01, -1.4642e+00,
          6.4493e-01, -3.9866e-01, -7.4431e-01, -1.4818e-01, -1.4473e-02,
          5.5707e-01,  3.0846e-01, -5.9594e-01, -7.0670e-01,  1.3991e+00],
        [ 4.5975e-01,  2.0010e+00,  1.5106e+00, -1.1241e+00, -1.9576e+00,
         -8.5908e-01, -7.9606e-01, -8.9820e-02, -4.1429e-02,  1.2779e+00,
         -2.4308e+00,  1.0898e+00,  1.2595e+00, -1.5689e+00, -3.6244e-01],
        [-1.3892e+00, -3.9734e-01,  3.3677e-01,  1.2112e+00,  1.0961e+00,
          2.6969e-01,  3.2192e-01,

In [29]:
theta_values.dtype

torch.float32

In [31]:
print(model)

Model(
  (layers): ModuleList(
    (0): Linear(in_features=30, out_features=40, bias=True)
    (1): ReLU()
    (2): Linear(in_features=40, out_features=40, bias=True)
    (3): ReLU()
    (4): Linear(in_features=40, out_features=40, bias=True)
    (5): ReLU()
    (6): Linear(in_features=40, out_features=40, bias=True)
    (7): ReLU()
    (8): Linear(in_features=40, out_features=40, bias=True)
    (9): ReLU()
    (10): Linear(in_features=40, out_features=15, bias=True)
    (11): ReLU()
  )
)


In [32]:
theta_values

tensor([[ 2.3780e+00,  5.3356e-01,  6.1115e-01, -6.5489e-01,  9.0136e-01,
          2.3947e-01, -1.7630e+00, -1.1065e+00,  2.5753e-01, -5.2407e-01,
         -7.8436e-02, -3.0203e+00, -2.7010e+00,  1.9684e+00,  4.0871e-01],
        [ 1.1824e+00,  9.5502e-01,  1.9165e+00,  1.0104e+00, -1.1905e+00,
          1.1722e+00,  1.8733e+00, -1.1290e+00,  5.0113e-01,  4.0206e-01,
          4.7761e-01, -1.8104e+00, -2.4886e-01,  5.5884e-01, -3.7427e-01],
        [-3.5849e-01, -1.1035e+00,  1.0169e+00,  1.9995e+00,  4.1886e-01,
          4.7412e-01,  3.1542e-01,  7.9115e-01, -1.4866e+00,  1.2596e+00,
         -1.6015e+00, -2.4057e-02,  2.0740e+00,  3.9365e-01,  1.6300e+00],
        [ 2.9588e-01,  2.0562e+00, -1.5897e+00, -9.9945e-01, -6.4634e-01,
         -3.1422e-01,  2.3146e-01,  5.0547e-01, -1.9168e+00,  4.7511e-01,
          1.5183e+00,  1.1625e+00, -8.8615e-01, -8.1641e-01,  9.8739e-01],
        [ 4.5780e-01, -1.8590e-01, -7.1072e-01,  4.7040e-01,  2.8612e-01,
         -1.6185e+00, -5.7648e-01,

In [33]:
theta_values.requires_grad

False

In [35]:
inputs.requires_grad

False

In [36]:
outputs.requires_grad

True

In [37]:
targets.requires_grad

False