In [1]:
# set the random seed 
import numpy as np
np.random.seed(42)

In [2]:
# give 50 random 10-dimensional features and 10 random rewards
np.random.seed(42)
features = np.random.rand(500, 10)
rewards = 10*np.random.rand(500, 1)

In [3]:
features

array([[3.74540119e-01, 9.50714306e-01, 7.31993942e-01, ...,
        8.66176146e-01, 6.01115012e-01, 7.08072578e-01],
       [2.05844943e-02, 9.69909852e-01, 8.32442641e-01, ...,
        5.24756432e-01, 4.31945019e-01, 2.91229140e-01],
       [6.11852895e-01, 1.39493861e-01, 2.92144649e-01, ...,
        5.14234438e-01, 5.92414569e-01, 4.64504127e-02],
       ...,
       [4.75100341e-01, 8.97955216e-01, 5.25049340e-01, ...,
        2.05980036e-01, 9.43415268e-04, 3.92650516e-02],
       [9.77283823e-01, 2.42353695e-01, 6.63310710e-01, ...,
        6.00251410e-01, 7.31250589e-01, 7.69746623e-01],
       [9.75410368e-01, 5.73563280e-01, 3.41641113e-01, ...,
        3.27842838e-01, 8.15745381e-01, 5.97312378e-01]])

In [4]:
# give 10-dimensional random weights 
# set the random seed
np.random.seed(42)
theta = np.random.rand(10, 1).reshape(1,-1)
theta

array([[0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864,
        0.15599452, 0.05808361, 0.86617615, 0.60111501, 0.70807258]])

In [5]:
#v = (features @ theta.T).reshape(1,-1)

In [6]:
features = [np.random.rand(20,10) for i in range(10000)]

In [7]:
rewards = [10*np.random.rand(20,1).reshape(1,-1) for i in range(10000)]

In [8]:
np.save('features.npy', features)

In [9]:
np.save('linear_data/theta.npy', theta)

In [10]:
np.save('linear_data/rewards.npy', rewards)

In [11]:
theta

array([[0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864,
        0.15599452, 0.05808361, 0.86617615, 0.60111501, 0.70807258]])

In [13]:
features[0] @ theta.T

array([[2.66131965],
       [1.8346095 ],
       [2.10736453],
       [2.15785084],
       [2.99301253],
       [2.79887389],
       [1.60084431],
       [2.75765083],
       [2.30546575],
       [2.20218659],
       [2.78759274],
       [2.71407704],
       [2.40063147],
       [1.89320984],
       [2.51576761],
       [2.2908628 ],
       [1.9434175 ],
       [2.59891711],
       [3.93801954],
       [1.77025654]])

In [1]:
import numpy as np  
TRUE_THETA = np.load('linear_data/theta.npy')

In [2]:
TRUE_THETA

array([[0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864,
        0.15599452, 0.05808361, 0.86617615, 0.60111501, 0.70807258]])