In [1]:
# set the random seed 
import numpy as np
np.random.seed(42)

In [2]:
# give 50 random 10-dimensional features and 10 random rewards
np.random.seed(42)
features = np.random.rand(500, 10)
rewards = 10*np.random.rand(500, 1)

In [3]:
# give 10-dimensional random weights 
# set the random seed
np.random.seed(42)
theta = np.random.rand(10, 1).reshape(1,-1)
theta

array([[0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864,
        0.15599452, 0.05808361, 0.86617615, 0.60111501, 0.70807258]])

In [4]:
#v = (features @ theta.T).reshape(1,-1)

In [21]:
features = [np.random.rand(20,10) for i in range(10000)]

In [52]:
rewards = [10*np.random.rand(20,1).reshape(1,-1) for i in range(10000)]

In [43]:
np.save('features.npy', features)

In [49]:
np.save('linear_data/theta.npy', theta)

In [ ]:
np.save('linear_data/rewards.npy', rewards)

In [48]:
theta

array([[0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864,
        0.15599452, 0.05808361, 0.86617615, 0.60111501, 0.70807258]])

In [53]:
rewards

[array([[6.96441533, 8.72742225, 8.2027955 , 9.36546594, 4.52333146,
         3.65011031, 7.15078596, 8.17053965, 7.696395  , 0.178979  ,
         1.31675488, 3.07736466, 5.9591961 , 1.16384656, 5.77542512,
         3.13751062, 7.29975485, 0.63603697, 9.08028713, 1.22926822]]),
 array([[4.82291301, 7.42355689, 1.32570641, 6.10764636, 7.70565468,
         1.54886606, 7.3325269 , 8.34395427, 3.33717117, 1.07184857,
         9.01600628, 4.9686189 , 7.08753208, 3.48786459, 2.69507679,
         9.70816218, 7.01788338, 6.39132596, 3.47885468, 7.51162833]]),
 array([[4.82462078, 7.63777195, 6.35458876, 1.46836524, 0.52535085,
         3.51132269, 4.49125423, 7.71383546, 3.37811427, 1.77425806,
         9.80014879, 0.76875162, 0.08863834, 3.98344907, 5.5904927 ,
         9.21100631, 9.68050873, 2.93067445, 6.2917381 , 7.62450318]]),
 array([[7.71673779e+00, 4.94810108e+00, 6.42199468e+00, 4.28828475e+00,
         9.76676551e+00, 8.25499198e+00, 2.92102552e+00, 2.97118402e-03,
         1.343187

In [1]:
import numpy as np  
TRUE_THETA = np.load('linear_data/theta.npy')

In [2]:
TRUE_THETA

array([[0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864,
        0.15599452, 0.05808361, 0.86617615, 0.60111501, 0.70807258]])