In [1]:
import os

os.environ["KMP_DUPLICATE_LIB_OK"]="TRUE"
import numpy as np
import torch
import random
import math 
import copy
import random
import argparse
import torch.optim as optim
import torch.nn as nn
import modeldefine
import numpy as np
from scipy.optimize import minimize
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
print(device)

cuda:0


In [2]:
alpha = 0.01

def UCB(A, phi):
    #### ucb term
    phi = phi.view(-1,1)
    try:
        tmp, LU = torch.linalg.solve(phi,A)
    except:
        A = A.detach().numpy()
        phi2 = phi.detach().numpy()
        tmp = torch.Tensor(np.linalg.solve(A, phi2))

    return torch.sqrt(torch.matmul(torch.transpose(phi,1,0), tmp))

def calculate_v(contextinfo_list, A, theta):
    vj_list = []
    feature_list = []
    for i in contextinfo_list:
        feature = model(i.to(device)).cpu()
        first_item =  torch.mm( feature.view(1,-1) , theta)
        second_item = alpha * UCB(A, feature)
        vj_list.append((first_item + second_item).item())
        feature_list.append(feature.detach().numpy())
    return np.array(vj_list), feature_list

def update_A(A, info_subset):
    for i in info_subset:
        i = torch.tensor(i, dtype=torch.float32,device=device)
        feature = model(i.to(device)).view(1,-1).cpu()
        A = A + torch.mm(feature.t(), feature)
    return A

# 这里调小utility 
def prob(vj_list):
    sum = np.sum(np.exp(vj_list)) + 1
    return [np.exp(vj_list[i]) / sum for i in range(len(vj_list))]  

def revenue(vj_list, reward_list):
    sum = np.sum(np.exp(vj_list)) + 1
    return np.sum(np.multiply(np.exp(vj_list), reward_list) / sum)

def assort(contextinfo_list, reward_list, vj_list, feature_list):
    length = len(contextinfo_list)
    # sort the contextinfo_list and vj with descending order of reward_list
    sorted_list = sorted(zip(contextinfo_list, vj_list, reward_list, feature_list), key=lambda x: x[2], reverse=True)
    
    contextinfo_list = [x[0] for x in sorted_list]
    vj_list = [x[1] for x in sorted_list]
    reward_list = [x[2] for x in sorted_list]
    feature_list = [x[3] for x in sorted_list]

    # calculate the optimal assortment
    optimal_assort = []
    optimal_reward = revenue(vj_list[:1], reward_list[:1])
    index = 1 
    for i in range(2,length):
        if revenue(vj_list[:i], reward_list[:i]) >= optimal_reward:
            optimal_reward = revenue(vj_list[:i], reward_list[:i])
        else:
            index = i - 1 
            break
    return contextinfo_list[:index], feature_list[:index], vj_list[:index], reward_list[:index]

# this is for the non_linear purchase model when v = x dot theta
def sigmoid(x):
    return 1 / (1 + np.exp(-1*x))

def get_nonlinear_purchase(feature_list):
    true_Vlist = [(TRUE_THETA @ sigmoid(feature_list[i]).reshape(-1,1)).item() for  i in range(len(feature_list))]
    prob_list = prob(true_Vlist)

    # sample item according to prob_list
    if random.uniform(0,1) < 1 - np.sum(prob_list):
        return np.array([0 for i in range(len(feature_list))])
    else:
        returnlist = [0 for i in range(len(feature_list))]
        indexchoose = random.choices([i for i in range(len(prob_list))], weights = prob_list)[0]
        returnlist[indexchoose] = 1
        return np.array(returnlist)

In [3]:
lambd = 0.1
def likelihood(theta, feature_list ,y_list):
    # feature's dimension is len * dimension , theta is 1*dimension
    v_list = np.matmul(feature_list, theta.T).reshape(-1)
    ln_prob = np.log(prob(v_list))
    summation = ln_prob * y_list
    return -1 * np.sum(summation)

def likelihood_derivative(theta, feature_list, y_list):
    v_list = np.matmul(feature_list, theta.T).reshape(-1)
    prob_list = prob(v_list)
    summation = np.matmul(np.array(feature_list).T, (y_list - prob_list))
    return -1 * summation

def likelihood_array(theta, feature_list_list, y_list_list):
    summation =  0.5 * lambd * np.dot(theta, theta)
    for i in range(len(feature_list_list)):
        summation += likelihood(theta, feature_list_list[i], y_list_list[i])
    return summation

def likelihood_derivative_array(theta, feature_list_list, y_list_list):
    summation = 0.5 * lambd * theta
    for i in range(len(feature_list_list)):
        summation += likelihood_derivative(theta, feature_list_list[i], y_list_list[i])
    return summation

In [14]:
class CustomLikelihoodLoss(nn.Module): 
    def __init__(self, theta_list):
        super(CustomLikelihoodLoss, self).__init__()
        self.theta_list = theta_list

    def forward(self, output_list, y_list):
        loss = 0
        index = 0
        for output in output_list:  
            y = torch.tensor(y_list[index]).to(device).view(-1,1)
            theta = torch.tensor(self.theta_list[index], dtype= torch.float32).to(device) 
            v = torch.mm(output, theta.view(-1,1)) 
            prob = torch.exp(v) / (torch.sum(torch.exp(v)) + 1)  
            loss += torch.sum(torch.log(prob) * y)  
            index += 1  
        return -loss 

class CustomLikelihoodLoss2(nn.Module):
    def __init__(self, theta_list):
        super(CustomLikelihoodLoss2, self).__init__()
        self.theta_list = theta_list
     
    def forward(self, output_list, y_list):
        loss = 0
        index = 0
        for output in output_list:
            y = torch.tensor(y_list[index]).to(device).view(-1,1)
            theta = torch.tensor(self.theta_list[index], dtype= torch.float32).to(device)
            v = torch.mm(output, theta.view(-1,1))
            prob = torch.exp(v) / (torch.sum(torch.exp(v)) + 1)
            # ce loss between prob and y
            loss += torch.sum(-y * torch.log(prob) - (1-y) * torch.log(1-prob))
            index += 1
        return 100*loss/len(output_list) 


In [5]:
# this block is only used for linear model revenue calculation
def calculate_sigmoid_v(contextinfo_list, A, theta):
    vj_list = []
    feature_list = []
    for i in contextinfo_list:
        feature = sigmoid(i)
        first_item =  torch.mm( feature.view(1,-1) , theta)

        vj_list.append(first_item.item())
        feature_list.append(feature.detach().numpy())
    return np.array(vj_list), feature_list

# 真实情况乱下的theta，feature
def get_true_sigmoid_ass(context, profit):
    
    v_array = np.array(sigmoid(context) @ TRUE_THETA.T ).reshape(-1)
    assortment, ass_features, v_list, profit_list = assort(context, profit.tolist()[0], v_array.tolist() , sigmoid(context))
    true_probablility = np.array(prob(v_list))
    revenue = np.dot(true_probablility, np.array(profit_list))
    return revenue


def get_assortment_revenue(assortment, profit):
    v_array = np.array(sigmoid(np.array(assortment)) @ TRUE_THETA.T ).reshape(-1)
    true_probablility = np.array(prob(v_array))
    revenue = np.dot(true_probablility, np.array(profit))
    return revenue

In [41]:
import modeldefine
import torch.optim as optim
model = modeldefine.Model(5,10,10,3).to(device)
# 10 20 20 20 20 20  5
optimizer = optim.Adam(model.parameters(), lr=0.001)

tensor([ 5, 10, 10, 10, 10], dtype=torch.int32)


In [37]:
print(model)

Model(
  (layers): ModuleList(
    (0): Linear(in_features=10, out_features=20, bias=True)
    (1): ReLU()
    (2): Linear(in_features=20, out_features=20, bias=True)
    (3): ReLU()
    (4): Linear(in_features=20, out_features=20, bias=True)
    (5): ReLU()
    (6): Linear(in_features=20, out_features=10, bias=True)
    (7): ReLU()
  )
)


In [38]:
# data reader
CONTEXT_ARRAY = np.load('nonlinear_data/features.npy') 
REWARD_ARRAY = np.load('nonlinear_data/rewards.npy')
TRUE_THETA = np.load('nonlinear_data/theta.npy')

In [42]:
data_length = len(CONTEXT_ARRAY)

# define the hyperparameters
input_size = 20
hidden_size = 20
output_size = 10
num_layers = 10

beta = 0.1

H = 100

# initialize the parameters

theta = np.random.randn(output_size) / np.sqrt(output_size)
#theta = TRUE_THETA
LAMBDA = lambd * torch.eye(output_size, dtype=torch.float32)

ass_list = []
feature_list = []
purchase_list = []
theta_list = []

revenue_list1 = []
revenue_list2 = []
true_profit_list = []

for t in range(0, 2000):
    context = CONTEXT_ARRAY[t]
    profit = REWARD_ARRAY[t]

    theta_tensor = torch.tensor(theta.reshape(-1,1), dtype=torch.float32)
    v_array,initial_feature = calculate_v(torch.tensor(context,dtype=torch.float32), LAMBDA, theta_tensor)
    assortment, ass_features, vv_list , reward = assort(context, profit.tolist()[0], v_array.tolist() , initial_feature)
    purchase_vector = get_nonlinear_purchase(assortment)
    
    # calculate the ideal 
    expected_revenue1 = get_true_sigmoid_ass(context, profit)
    revenue_list1.append(expected_revenue1)
    true_profit_list.append(np.dot(np.array(purchase_vector), reward))
    revenue_list2.append(get_assortment_revenue(assortment, reward))

    # add to list
    ass_list.append(np.array(assortment))
    feature_list.append(np.array(ass_features))
    purchase_list.append(purchase_vector)

    # update the parameters
    LAMBDA = update_A(LAMBDA, assortment)
    
    # update theta using MLE
    initial_guess = theta
    
    try:
        result = minimize(likelihood_array, initial_guess, args=(feature_list, purchase_list), method='SLSQP', 
                  constraints={'type':'eq', 'fun': likelihood_derivative_array, 'args':(feature_list, purchase_list)})
        theta = result.x
    except: 
        print('error occured')
        theta = theta
    theta_list.append(theta)
    
    #theta_list.append(TRUE_THETA)
    # update the neural networks
    if t % H == 99:
        #a_list = ass_list[-1*H:]
        #y_list = purchase_list[-1*H:]

        a_list = ass_list[:]
        y_list = purchase_list[:]

        loss_function = CustomLikelihoodLoss2(theta_list)
        epochs = 3
     
        for epoch in range(epochs):
            output_list = [model(torch.tensor(a,dtype = torch.float32).to(device)) for a in a_list]
            loss = loss_function(output_list, y_list)
            #if (epoch == epochs-1): 
            print(f"Epoch [{epoch+1}/{epochs}], Loss: {loss.item()}")
            
            optimizer.zero_grad()
            loss.backward()
            optimizer.step()
        #theta_list = []

Epoch [1/3], Loss: 181.3025665283203
Epoch [2/3], Loss: 173.05751037597656
Epoch [3/3], Loss: 167.21334838867188
Epoch [1/3], Loss: 183.3002471923828
Epoch [2/3], Loss: 180.98207092285156
Epoch [3/3], Loss: 178.92214965820312
Epoch [1/3], Loss: 186.233154296875
Epoch [2/3], Loss: 185.10794067382812
Epoch [3/3], Loss: 184.09063720703125
Epoch [1/3], Loss: 194.12619018554688
Epoch [2/3], Loss: 193.31434631347656
Epoch [3/3], Loss: 192.449462890625
Epoch [1/3], Loss: 197.94351196289062
Epoch [2/3], Loss: 197.15145874023438
Epoch [3/3], Loss: 196.41094970703125
Epoch [1/3], Loss: 198.4515838623047
Epoch [2/3], Loss: 197.96022033691406
Epoch [3/3], Loss: 197.4444580078125
Epoch [1/3], Loss: 201.03878784179688
Epoch [2/3], Loss: 200.49627685546875
Epoch [3/3], Loss: 199.9710235595703
Epoch [1/3], Loss: 201.60047912597656
Epoch [2/3], Loss: 201.16429138183594
Epoch [3/3], Loss: 200.7367706298828
Epoch [1/3], Loss: 203.78372192382812
Epoch [2/3], Loss: 203.36842346191406
Epoch [3/3], Loss: 202

In [12]:
loss_function(output_list, y_list)

tensor(151.2813, device='cuda:0', grad_fn=<AddBackward0>)

[]

In [43]:
np.save('nonlinear_data/record/true_revenue_list1.npy', np.array(revenue_list1))
np.save('nonlinear_data/record/simulate_revenue_list2.npy', np.array(revenue_list2))
np.save('nonlinear_data/record/purchase_revenue_list.npy', np.array(true_profit_list))

In [44]:
print(prob((sigmoid(ass_list[100]) @ TRUE_THETA.reshape(10,1)).reshape(1,-1)))
print(prob(calculate_v(torch.tensor(ass_list[100],dtype=torch.float32), LAMBDA, theta_tensor)[0]))

[array([0.05709873, 0.17355199, 0.09550531, 0.17509119, 0.47714522])]
[0.03953770013400015, 0.29076432845604594, 0.14791259908649967, 0.19310983423110534, 0.2642805664930024]


In [45]:
print(prob((sigmoid(ass_list[102]) @ TRUE_THETA.reshape(10,1)).reshape(1,-1)))
print(prob(calculate_v(torch.tensor(ass_list[102],dtype=torch.float32), LAMBDA, theta_tensor)[0]))


[array([0.29278136, 0.29572917, 0.15751003, 0.20177294])]
[0.18374733567609156, 0.15668775102185364, 0.24629200433566073, 0.28258740699866153]


In [15]:
purchase_list[99]

array([1, 0])

In [20]:
for i in range(100):
    print(np.sum(prob((sigmoid(ass_list[i]) @ TRUE_THETA.reshape(10,1)).reshape(-1))))
    print(prob((sigmoid(ass_list[i]) @ TRUE_THETA.reshape(10,1)).reshape(-1)))
    print(purchase_list[i])

0.9666390717683387
[0.20607739076655648, 0.3339939081805579, 0.06752884498776254, 0.1912444842074085, 0.16779444362605334]
[0 0 0 1 0]
0.9529385568706941
[0.7876107612086405, 0.16532779566205363]
[1 0]
0.949341956322374
[0.31995421892121595, 0.629387737401158]
[0 1]
0.9244432185883495
[0.2337638764724094, 0.6906793421159402]
[0 1]
0.7817027880523651
[0.7817027880523651]
[1]
0.9572522398640111
[0.45723667875151275, 0.5000155611124983]
[1 0]
0.8152201067953293
[0.8152201067953293]
[1]
0.6743599465502335
[0.6743599465502335]
[0]
0.8968495394982787
[0.46734801779608154, 0.42950152170219724]
[0 1]
0.911398970830402
[0.339960522796622, 0.5714384480337801]
[0 1]
0.9294057974116152
[0.4887144635952136, 0.44069133381640163]
[0 1]
0.9180354068750853
[0.9180354068750853]
[0]
0.9127870161252808
[0.4996878296282541, 0.4130991864970267]
[0 1]
0.9711730179524126
[0.13193979101070302, 0.6373168750324629, 0.20191635190924673]
[0 1 0]
0.981459822260341
[0.06262255206362026, 0.1296842037179939, 0.2275462

In [19]:
np.sum(prob((sigmoid(ass_list[i]) @ TRUE_THETA.reshape(10,1)).reshape(-1)))

0.8548929116008221

In [16]:
[prob((sigmoid(ass_list[i]) @ TRUE_THETA.reshape(10,1)).reshape(1,-1)) for i in range(100)]

[[array([0.27334248, 0.34842051, 0.02233909, 0.15747049, 0.18755381])],
 [array([0.43513131, 0.16600242, 0.37851026])],
 [array([0.08758267, 0.36294585, 0.08480983, 0.14495592, 0.18499692,
         0.12530226])],
 [array([0.029264  , 0.18857597, 0.11421447, 0.29338097, 0.18762713,
         0.05005263, 0.12838346])],
 [array([0.15364819, 0.83562979])],
 [array([0.54962103, 0.27152416, 0.16614205])],
 [array([0.16249619, 0.30244132, 0.20787825, 0.25651734, 0.05113159])],
 [array([0.08767528, 0.7139933 , 0.17904716])],
 [array([0.27273083, 0.56526123, 0.12235642])],
 [array([0.35186198, 0.62465737])],
 [array([0.16446789, 0.47926665, 0.20793581, 0.13315316])],
 [array([0.43616794, 0.03669656, 0.0887331 , 0.12443575, 0.06812428,
         0.13870315, 0.10159803])],
 [array([0.27086889, 0.16342173, 0.23450739, 0.14257266, 0.17533397])],
 [array([0.04874252, 0.48972837, 0.33135392, 0.12062766])],
 [array([0.08531741, 0.12845802, 0.45575668, 0.31897941])],
 [array([0.47217555, 0.11057679, 0.19

In [14]:
purchase_list

[array([0, 1, 0, 0, 0]),
 array([0, 0, 1]),
 array([0, 0, 0, 0, 1, 0]),
 array([0, 0, 0, 1, 0, 0, 0]),
 array([0, 1]),
 array([0, 1, 0]),
 array([0, 1, 0, 0, 0]),
 array([0, 1, 0]),
 array([1, 0, 0]),
 array([1, 0]),
 array([0, 0, 0, 1]),
 array([0, 0, 0, 0, 0, 1, 0]),
 array([0, 0, 0, 1, 0]),
 array([0, 1, 0, 0]),
 array([0, 0, 0, 1]),
 array([1, 0, 0, 0]),
 array([1, 0, 0, 0, 0, 0]),
 array([0, 1, 0]),
 array([0, 0, 1]),
 array([0, 1, 0, 0, 0]),
 array([0, 1]),
 array([1, 0, 0, 0]),
 array([0, 0, 1, 0, 0, 0]),
 array([0, 0, 0, 1, 0, 0]),
 array([0, 0, 1, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 1]),
 array([0, 1, 0, 0, 0]),
 array([0, 0, 1, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 1]),
 array([0, 0, 0, 0, 0, 1]),
 array([1, 0, 0, 0, 0]),
 array([0, 0, 0, 1, 0, 0]),
 array([0, 0, 1, 0, 0]),
 array([0, 0, 0, 0, 1]),
 array([0, 0, 0, 1, 0, 0]),
 array([0, 1, 0, 0, 0]),
 array([1, 0, 0, 0]),
 array([1, 0, 0, 0]),
 array([0, 1, 0, 0]),
 array([0, 0, 1]),
 array([0, 0, 1]),
 array([0, 0, 0, 0, 0, 1, 0])

In [ ]:
# regret calculate
# ult - 1  让不购买概率最大
# matolotlib linear  10000 epoch 
# 真实情况下的expected revenue， theta， Truetheta
# expected 和 assortment 的revenue 顾客的purchase 
# 


