In [1]:
import numpy as np
np.random.seed(42)

In [2]:
np.random.rand()

0.3745401188473625

In [22]:
np.random.seed(42)
#features = 3*np.random.randn(500,10)
#rewards = 10 * np.random.rand(500,1)

features = [2*np.random.randn(20,10) - 1 for i in range(10000)]
rewards = [10*np.random.rand(20,1).reshape(1,-1) for i in range(10000)]

In [23]:
# sigmoid function
def sigmoid(x):
    return 1 / (1 + np.exp(-x))
def sigmoid_list(x):
    return np.array([sigmoid(i) for i in x])

In [24]:
theta = np.random.rand(10,1).reshape(1,-1)

In [25]:
theta

array([[0.26730065, 0.65786584, 0.69499535, 0.48432088, 0.74675553,
        0.2463713 , 0.12375139, 0.59859644, 0.39209949, 0.80429024]])

In [26]:
sigmoid(features[0]) @ theta.T

array([[2.24695782],
       [0.70516944],
       [1.17688051],
       [1.68686302],
       [1.30225979],
       [2.11405828],
       [1.61535428],
       [1.73700765],
       [1.86490191],
       [1.33789084],
       [1.17095692],
       [1.96033259],
       [1.74616723],
       [1.11113801],
       [1.80850458],
       [1.82086638],
       [2.43986114],
       [2.30373735],
       [0.99286705],
       [1.4567378 ]])

In [27]:
np.save('nonlinear_data/features.npy', features)
np.save('nonlinear_data/rewards.npy', rewards)
np.save('nonlinear_data/theta.npy', theta)

In [14]:
features = np.load('nonlinear_data/features.npy')    

In [17]:
sigmoid(features[0]) @ theta.T

array([[2.93589423],
       [1.66005668],
       [2.23384566],
       [2.37417342],
       [2.1299019 ],
       [2.79988452],
       [2.40457323],
       [2.28414283],
       [2.66070183],
       [2.35837326],
       [2.28364967],
       [2.68886523],
       [2.48683945],
       [2.02386048],
       [2.49917223],
       [2.64523068],
       [2.9269907 ],
       [2.96519038],
       [1.97149844],
       [2.36573891]])

In [58]:
features[0][0]

array([ 1.49014246, -0.4147929 ,  1.94306561,  4.56908957, -0.70246012,
       -0.70241087,  4.73763845,  2.30230419, -1.40842316,  1.62768013])