In [42]:
import numpy as np
np.random.seed(42)

In [ ]:
np.random.rand()

In [88]:
np.random.seed(42)
#features = 3*np.random.randn(500,10)
#rewards = 10 * np.random.rand(500,1)

features = [10*np.random.randn(20,10)-5 for i in range(10000)]
rewards = [10*np.random.rand(20,1).reshape(1,-1) for i in range(10000)]

In [89]:
# sigmoid function
def sigmoid(x):
    return 1 / (1 + np.exp(-x))
def sigmoid_list(x):
    return np.array([sigmoid(i) for i in x])

In [90]:
theta = np.random.rand(10,1).reshape(1,-1)

In [91]:
theta

array([[0.26730065, 0.65786584, 0.69499535, 0.48432088, 0.74675553,
        0.2463713 , 0.12375139, 0.59859644, 0.39209949, 0.80429024]])

In [93]:
sigmoid(features[0]) @theta.T

array([[2.35351899],
       [0.12980743],
       [0.41611247],
       [1.4235569 ],
       [0.93430527],
       [2.2492716 ],
       [1.6360929 ],
       [1.44444621],
       [1.46446038],
       [0.72456003],
       [0.2499179 ],
       [1.66307011],
       [1.72790765],
       [0.84133689],
       [1.29928921],
       [1.30119548],
       [2.84665768],
       [1.79793926],
       [0.70563461],
       [0.78709117]])

In [61]:
np.save('nonlinear_data/features.npy', features)
np.save('nonlinear_data/rewards.npy', rewards)
np.save('nonlinear_data/theta.npy', theta)

In [53]:
features = np.load('nonlinear_data/features.npy')    

In [57]:
sigmoid(features[0][0])

array([0.81609965, 0.39776343, 0.87468855, 0.98973899, 0.33126701,
       0.33127792, 0.99131675, 0.90906769, 0.19648288, 0.83585159])

In [58]:
features[0][0]

array([ 1.49014246, -0.4147929 ,  1.94306561,  4.56908957, -0.70246012,
       -0.70241087,  4.73763845,  2.30230419, -1.40842316,  1.62768013])