In [1]:
import numpy as np 
np.random.seed(42)
import random

In [44]:
import numpy as np
import matplotlib.pyplot as plt

# 生成1000个随机起点和终点
start_points = np.linspace(0, 10, 101)
end_points = start_points[-100:]
end_points

array([ 0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,  1.1,
        1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,  2.2,
        2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,  3.3,
        3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,  4.4,
        4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,  5.5,
        5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,  6.6,
        6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,  7.7,
        7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,  8.8,
        8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,  9.9,
       10. ])

In [45]:
lista = []
for i in range(100):
    lista.append(np.random.uniform(start_points[i],end_points[i],10))
lista

[array([0.07027829, 0.00420058, 0.09068728, 0.04844728, 0.0460327 ,
        0.05664666, 0.01493845, 0.0469166 , 0.08311272, 0.00154825]),
 array([0.12729172, 0.10024546, 0.14157113, 0.17283155, 0.17987718,
        0.19451898, 0.16085046, 0.12546269, 0.19241479, 0.17753158]),
 array([0.25744285, 0.26956402, 0.29243164, 0.2712394 , 0.23683745,
        0.27130282, 0.20402782, 0.23864156, 0.2406323 , 0.21668382]),
 array([0.30230855, 0.31333812, 0.36546215, 0.38022888, 0.39882035,
        0.33463635, 0.35993792, 0.3937145 , 0.31670418, 0.37176456]),
 array([0.47549787, 0.40889755, 0.48612494, 0.4813105 , 0.4033403 ,
        0.40910844, 0.40491269, 0.43347435, 0.4509289 , 0.45323477]),
 array([0.52676668, 0.59115969, 0.53682628, 0.50455502, 0.53002271,
        0.55311094, 0.54082218, 0.52738425, 0.51313232, 0.58191645]),
 array([0.69961452, 0.63295421, 0.6381621 , 0.66180375, 0.67184415,
        0.63920295, 0.69049295, 0.6560004 , 0.64503901, 0.66466728]),
 array([0.79528038, 0.77945523, 0.

In [46]:
np.array(random.sample(lista,8))

array([[8.64906097, 8.62166866, 8.61697234, 8.60001577, 8.6718238 ,
        8.61110972, 8.62438391, 8.62978763, 8.65603799, 8.63979573],
       [4.83083551, 4.88844965, 4.86762337, 4.83409164, 4.85435344,
        4.88405359, 4.88833683, 4.81603939, 4.83395731, 4.83352232],
       [5.99035593, 5.92389866, 5.92065132, 5.99698208, 5.90250041,
        5.97857822, 5.932137  , 5.9037488 , 5.99178025, 5.91396423],
       [4.07040857, 4.0260116 , 4.0941905 , 4.05300885, 4.08313241,
        4.03650457, 4.01002113, 4.06737116, 4.00077596, 4.0475293 ],
       [7.7818212 , 7.70056521, 7.7991997 , 7.71828938, 7.7470249 ,
        7.78720297, 7.72250404, 7.74767952, 7.71325822, 7.73950763],
       [1.91415489, 1.97103876, 1.96611306, 1.90439716, 1.98365938,
        1.92487433, 1.94322271, 1.96679337, 1.94294188, 1.94412878],
       [7.35333381, 7.38579952, 7.37367502, 7.32156091, 7.33992993,
        7.35078942, 7.38102058, 7.38391216, 7.39097183, 7.35092453],
       [7.46942747, 7.41118004, 7.4565289

In [47]:
features = [np.array(random.sample(lista,8)) for i in range(10000)]

In [48]:
theta = np.random.rand(10, 1).reshape(1,-1)
# theta /10 
theta = theta / 5
theta

array([[0.08004382, 0.11538443, 0.17098339, 0.19484851, 0.0878985 ,
        0.01208938, 0.14982312, 0.11303465, 0.08957827, 0.06185378]])

In [55]:
features[0]

array([[1.58433324, 1.57180062, 1.59436337, 1.56934669, 1.59404014,
        1.55545126, 1.56002186, 1.59769711, 1.56421291, 1.50307866],
       [4.79403162, 4.72936764, 4.74157036, 4.77869568, 4.75460246,
        4.75470281, 4.70533402, 4.73985997, 4.72707337, 4.79993351],
       [5.28327587, 5.21215112, 5.28100693, 5.24812762, 5.24506234,
        5.24238998, 5.25092116, 5.29450506, 5.25482038, 5.29531775],
       [9.86543063, 9.80800326, 9.82423298, 9.87736793, 9.85286859,
        9.89279691, 9.84287514, 9.88698124, 9.84489554, 9.89792483],
       [4.66034176, 4.6389123 , 4.65576424, 4.65767608, 4.61655353,
        4.64027324, 4.63434306, 4.64009027, 4.67611106, 4.64825384],
       [5.74728045, 5.78997596, 5.73361597, 5.72943217, 5.78727963,
        5.77969877, 5.75149798, 5.71307347, 5.72150715, 5.7656228 ],
       [2.17959732, 2.16096936, 2.11105863, 2.16277327, 2.11867463,
        2.15102159, 2.15291033, 2.18762034, 2.14624943, 2.12794424],
       [8.59869137, 8.53980432, 8.5331906

In [59]:
features[0][0] @theta.T

array([1.69290315])

In [58]:
features[0] @ theta.T

array([[ 1.69290315],
       [ 5.10775662],
       [ 5.65768435],
       [10.59775328],
       [ 4.99898825],
       [ 6.18002881],
       [ 2.3121188 ],
       [ 9.20863498]])

In [64]:
ut_list = [(features[i] @ theta.T).reshape(1,-1) for i in range(10000)]

In [65]:
ut_list

[array([[ 1.69290315,  5.10775662,  5.65768435, 10.59775328,  4.99898825,
          6.18002881,  2.3121188 ,  9.20863498]]),
 array([[ 6.18002881, 10.06586037,  2.53775529,  6.82939728,  7.03532036,
          5.32555164,  2.72758992,  5.54533751]]),
 array([[9.82797594, 1.3513309 , 6.29690466, 6.82939728, 1.01992534,
         6.63450749, 9.09217355, 7.57788543]]),
 array([[ 0.05086914,  2.09326886,  3.71738607,  6.63450749,  5.65768435,
          5.10775662, 10.16330299,  2.72758992]]),
 array([[3.49748685, 2.72758992, 8.24365823, 3.26727818, 1.45374026,
         8.78017701, 6.29690466, 2.21758771]]),
 array([[0.57634978, 4.77539329, 9.39646568, 0.27116027, 2.09326886,
         4.14125316, 3.49748685, 7.27497822]]),
 array([[9.82797594, 9.71946418, 0.38582377, 8.89486355, 0.71037738,
         5.10775662, 2.63585167, 5.65768435]]),
 array([[1.45374026, 9.20863498, 0.57634978, 0.05086914, 8.3263611 ,
         8.10527834, 9.27990689, 5.10775662]]),
 array([[8.99823919, 3.93217604, 7.78676

In [66]:
np.save('theta_gau.npy', theta)
np.save('features_uni.npy', features)

In [67]:
def prob(vj_list):
    sum = np.sum(np.exp(vj_list)) 
    return [np.exp(vj_list[i]) / sum for i in range(len(vj_list))]  

In [68]:
prob_list = [prob(ut_list[i])[0] for i in range(10000)]
prob_list 

[array([1.06309980e-04, 3.23315150e-03, 5.60346464e-03, 7.83251638e-01,
        2.89993694e-03, 9.44730535e-03, 1.97467658e-04, 1.95260726e-01]),
 array([1.81860223e-02, 8.85794377e-01, 4.76341508e-04, 3.48140750e-02,
        4.27746158e-02, 7.73825430e-03, 5.75920526e-04, 9.64039409e-03]),
 array([5.86500259e-01, 1.22154098e-04, 1.71689381e-02, 2.92416612e-02,
        8.76961311e-05, 2.40637041e-02, 2.81004510e-01, 6.18110776e-02]),
 array([3.86660516e-05, 2.98079944e-04, 1.51243910e-03, 2.79619614e-02,
        1.05278269e-02, 6.07446669e-03, 9.53024458e-01, 5.62101690e-04]),
 array([3.01985644e-03, 1.39837712e-03, 3.47714131e-01, 2.39887680e-03,
        3.91199628e-04, 5.94606273e-01, 4.96315693e-02, 8.39717425e-04]),
 array([1.29749520e-04, 8.64424736e-03, 8.78280876e-01, 9.56232813e-05,
        5.91419103e-04, 4.58483415e-03, 2.40846018e-03, 1.05264790e-01]),
 array([4.31816509e-01, 3.87412099e-01, 3.42471674e-05, 1.69845357e-01,
        4.73779751e-05, 3.84887703e-03, 3.24937143e-

In [69]:
import random
def get_purchase(problist):
    returnlist = [0 for i in range(len(problist))]
    indexchoose = random.choices([i for i in range(len(problist))], weights = problist)[0]
    returnlist[indexchoose] = 1
    return np.array(returnlist)

In [70]:
purchase_list = []
for i in range(10000):
    purchase_list.append(get_purchase(prob_list[i]))

In [71]:
prob_list
np.save('prob_list.npy', prob_list)

In [72]:
prob_list

[array([1.06309980e-04, 3.23315150e-03, 5.60346464e-03, 7.83251638e-01,
        2.89993694e-03, 9.44730535e-03, 1.97467658e-04, 1.95260726e-01]),
 array([1.81860223e-02, 8.85794377e-01, 4.76341508e-04, 3.48140750e-02,
        4.27746158e-02, 7.73825430e-03, 5.75920526e-04, 9.64039409e-03]),
 array([5.86500259e-01, 1.22154098e-04, 1.71689381e-02, 2.92416612e-02,
        8.76961311e-05, 2.40637041e-02, 2.81004510e-01, 6.18110776e-02]),
 array([3.86660516e-05, 2.98079944e-04, 1.51243910e-03, 2.79619614e-02,
        1.05278269e-02, 6.07446669e-03, 9.53024458e-01, 5.62101690e-04]),
 array([3.01985644e-03, 1.39837712e-03, 3.47714131e-01, 2.39887680e-03,
        3.91199628e-04, 5.94606273e-01, 4.96315693e-02, 8.39717425e-04]),
 array([1.29749520e-04, 8.64424736e-03, 8.78280876e-01, 9.56232813e-05,
        5.91419103e-04, 4.58483415e-03, 2.40846018e-03, 1.05264790e-01]),
 array([4.31816509e-01, 3.87412099e-01, 3.42471674e-05, 1.69845357e-01,
        4.73779751e-05, 3.84887703e-03, 3.24937143e-

In [73]:
purchase_list

[array([0, 0, 0, 1, 0, 0, 0, 0]),
 array([0, 1, 0, 0, 0, 0, 0, 0]),
 array([1, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 1, 0]),
 array([0, 0, 0, 0, 0, 1, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 1]),
 array([1, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 1, 0, 0]),
 array([1, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 1, 0, 0, 0, 0, 0, 0]),
 array([1, 0, 0, 0, 0, 0, 0, 0]),
 array([1, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 1, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 1]),
 array([0, 0, 0, 1, 0, 0, 0, 0]),
 array([1, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 1, 0, 0]),
 array([0, 0, 0, 0, 0, 1, 0, 0]),
 array([0, 1, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 1, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 1, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 1]),
 array([0, 0, 0, 0, 1, 0, 0, 0]),
 array([0, 0, 1, 0, 0, 0, 0, 0]),
 array([0, 0, 1, 0, 0, 0, 0, 0]),
 array([0, 1, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 1, 0]),
 array([0, 0, 0, 0, 0, 0, 1, 0]),
 array([0, 0, 0, 0, 0, 1, 0, 0]),
 array([0, 0, 

In [74]:
np.save('purchase_uni.npy', purchase_list)

In [75]:
prob_list[100]

array([0.00201751, 0.20554796, 0.68815717, 0.0014676 , 0.00118401,
       0.01411807, 0.06320868, 0.024299  ])