In [1]:
import numpy as np 
np.random.seed(42)
import random

In [12]:
import numpy as np
import matplotlib.pyplot as plt

# 生成1000个随机起点和终点
start_points = np.linspace(0, 10, 1001)
end_points = start_points[-1000:]
end_points

array([ 0.01,  0.02,  0.03,  0.04,  0.05,  0.06,  0.07,  0.08,  0.09,
        0.1 ,  0.11,  0.12,  0.13,  0.14,  0.15,  0.16,  0.17,  0.18,
        0.19,  0.2 ,  0.21,  0.22,  0.23,  0.24,  0.25,  0.26,  0.27,
        0.28,  0.29,  0.3 ,  0.31,  0.32,  0.33,  0.34,  0.35,  0.36,
        0.37,  0.38,  0.39,  0.4 ,  0.41,  0.42,  0.43,  0.44,  0.45,
        0.46,  0.47,  0.48,  0.49,  0.5 ,  0.51,  0.52,  0.53,  0.54,
        0.55,  0.56,  0.57,  0.58,  0.59,  0.6 ,  0.61,  0.62,  0.63,
        0.64,  0.65,  0.66,  0.67,  0.68,  0.69,  0.7 ,  0.71,  0.72,
        0.73,  0.74,  0.75,  0.76,  0.77,  0.78,  0.79,  0.8 ,  0.81,
        0.82,  0.83,  0.84,  0.85,  0.86,  0.87,  0.88,  0.89,  0.9 ,
        0.91,  0.92,  0.93,  0.94,  0.95,  0.96,  0.97,  0.98,  0.99,
        1.  ,  1.01,  1.02,  1.03,  1.04,  1.05,  1.06,  1.07,  1.08,
        1.09,  1.1 ,  1.11,  1.12,  1.13,  1.14,  1.15,  1.16,  1.17,
        1.18,  1.19,  1.2 ,  1.21,  1.22,  1.23,  1.24,  1.25,  1.26,
        1.27,  1.28,

In [15]:
lista = []
for i in range(1000):
    lista.append(np.random.uniform(start_points[i],end_points[i],10))
lista

[array([0.00294067, 0.00210319, 0.00765363, 0.00253026, 0.00865562,
        0.00102843, 0.00125955, 0.00979152, 0.00673839, 0.00846887]),
 array([0.01324329, 0.01676484, 0.01594242, 0.0160315 , 0.01682532,
        0.01575359, 0.01429062, 0.01275923, 0.01768581, 0.01226272]),
 array([0.02692354, 0.02233333, 0.0262533 , 0.02747078, 0.02218714,
        0.02059943, 0.02130974, 0.02605997, 0.02849446, 0.02044997]),
 array([0.03734151, 0.03341319, 0.03478528, 0.0392886 , 0.03331972,
        0.03465337, 0.03013682, 0.03081599, 0.03258592, 0.03027852]),
 array([0.04631375, 0.04426398, 0.04548145, 0.04174647, 0.04295932,
        0.04663824, 0.04965303, 0.04050417, 0.04890384, 0.04576881]),
 array([0.0556392 , 0.05500279, 0.05069394, 0.05089877, 0.05600912,
        0.05340959, 0.05917268, 0.05406591, 0.05143281, 0.05714719]),
 array([0.06293353, 0.0652547 , 0.06697833, 0.06900264, 0.06792191,
        0.06676361, 0.06679633, 0.06945925, 0.06295824, 0.06001112]),
 array([0.07271955, 0.07217891, 0.

In [28]:
np.array(random.sample(lista,8))

array([[0.01324329, 0.01676484, 0.01594242, 0.0160315 , 0.01682532,
        0.01575359, 0.01429062, 0.01275923, 0.01768581, 0.01226272],
       [7.14227149, 7.14389626, 7.14606458, 7.14755339, 7.14901653,
        7.14915473, 7.1477664 , 7.14228331, 7.14024809, 7.14383774],
       [7.37192802, 7.37627376, 7.3797942 , 7.37464403, 7.37817498,
        7.37507784, 7.3749584 , 7.37930423, 7.37889966, 7.377858  ],
       [9.67340225, 9.67318133, 9.67956528, 9.67789074, 9.67724009,
        9.67185963, 9.67909526, 9.6782787 , 9.67163642, 9.6787117 ],
       [9.91204268, 9.91545236, 9.91765352, 9.91895669, 9.91789712,
        9.91195267, 9.91599686, 9.91332173, 9.91009206, 9.91200221],
       [5.30520083, 5.3083025 , 5.30419249, 5.30193994, 5.30284853,
        5.30505164, 5.30531331, 5.30805581, 5.30791353, 5.30581367],
       [9.50063876, 9.50356418, 9.50601077, 9.50556116, 9.50404655,
        9.50429048, 9.5022677 , 9.50455883, 9.50953255, 9.50850453],
       [6.23522373, 6.2300722 , 6.2331659

In [29]:
features = [np.array(random.sample(lista,8)) for i in range(10000)]

In [38]:
theta = np.random.rand(10, 1).reshape(1,-1)
# theta /10 
theta = theta / 5
theta

array([[0.03743572, 0.16012473, 0.1944313 , 0.04295188, 0.03738239,
        0.09098701, 0.14955306, 0.05632012, 0.00397598, 0.10824413]])

In [39]:
ut_list = [(features[i] @ theta.T).reshape(1,-1) for i in range(10000)]

In [41]:
np.save('theta_gau.npy', theta)
np.save('features_uni.npy', features)

In [42]:
def prob(vj_list):
    sum = np.sum(np.exp(vj_list)) 
    return [np.exp(vj_list[i]) / sum for i in range(len(vj_list))]  

In [43]:
prob_list = [prob(ut_list[i])[0] for i in range(10000)]
prob_list 

[array([5.89596882e-03, 1.42662643e-03, 1.17189422e-01, 2.89742700e-01,
        4.84931021e-02, 2.99267222e-04, 3.11927946e-02, 5.05760119e-01]),
 array([0.09944705, 0.05413472, 0.03001208, 0.05606063, 0.07251709,
        0.68026468, 0.00439541, 0.00316835]),
 array([0.05923074, 0.00293156, 0.54634386, 0.09878184, 0.02727849,
        0.153677  , 0.03917414, 0.07258237]),
 array([0.0218164 , 0.17922995, 0.69080453, 0.00843374, 0.02580994,
        0.03904659, 0.00618461, 0.02867423]),
 array([0.00182826, 0.01717751, 0.10350746, 0.06911913, 0.14120124,
        0.00655357, 0.03039401, 0.63021881]),
 array([0.09492895, 0.01543801, 0.02508279, 0.22720533, 0.35949368,
        0.00894254, 0.26377765, 0.00513105]),
 array([0.181124  , 0.0008915 , 0.05147008, 0.08951848, 0.06812615,
        0.00071535, 0.38002634, 0.2281281 ]),
 array([0.01493442, 0.07120864, 0.0024326 , 0.606207  , 0.13426942,
        0.01253255, 0.12941626, 0.02899911]),
 array([9.38942742e-02, 2.60750255e-04, 4.95448820e-03, 

In [44]:
import random
def get_purchase(problist):
    returnlist = [0 for i in range(len(problist))]
    indexchoose = random.choices([i for i in range(len(problist))], weights = problist)[0]
    returnlist[indexchoose] = 1
    return np.array(returnlist)

In [45]:
purchase_list = []
for i in range(10000):
    purchase_list.append(get_purchase(prob_list[i]))

In [46]:
prob_list
np.save('prob_list.npy', prob_list)

In [47]:
purchase_list

[array([0, 0, 0, 1, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 1, 0, 0]),
 array([0, 0, 0, 0, 1, 0, 0, 0]),
 array([0, 0, 1, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 1]),
 array([0, 0, 0, 0, 1, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 1]),
 array([0, 1, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 1, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 1, 0]),
 array([0, 1, 0, 0, 0, 0, 0, 0]),
 array([1, 0, 0, 0, 0, 0, 0, 0]),
 array([1, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 1, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 1, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 1, 0, 0, 0, 0]),
 array([0, 0, 1, 0, 0, 0, 0, 0]),
 array([1, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 1, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 1, 0, 0]),
 array([0, 0, 0, 0, 1, 0, 0, 0]),
 array([0, 0, 0, 0, 1, 0, 0, 0]),
 array([0, 0, 0, 0, 1, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 1]),
 array([0, 0, 0, 0, 0, 0, 0, 1]),
 array([0, 1, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 1, 0, 0]),
 array([0, 0, 1, 0, 0, 0, 0, 0]),
 array([0, 0, 1, 0, 0, 0, 0, 0]),
 array([1, 0, 

In [48]:
np.save('purchase_uni.npy', purchase_list)

In [55]:
purchase_list

[array([0, 0, 0, 1, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 1, 0, 0]),
 array([0, 0, 0, 0, 1, 0, 0, 0]),
 array([0, 0, 1, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 1]),
 array([0, 0, 0, 0, 1, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 1]),
 array([0, 1, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 1, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 1, 0]),
 array([0, 1, 0, 0, 0, 0, 0, 0]),
 array([1, 0, 0, 0, 0, 0, 0, 0]),
 array([1, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 1, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 1, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 1, 0, 0, 0, 0]),
 array([0, 0, 1, 0, 0, 0, 0, 0]),
 array([1, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 1, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 1, 0, 0]),
 array([0, 0, 0, 0, 1, 0, 0, 0]),
 array([0, 0, 0, 0, 1, 0, 0, 0]),
 array([0, 0, 0, 0, 1, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 1]),
 array([0, 0, 0, 0, 0, 0, 0, 1]),
 array([0, 1, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 1, 0, 0]),
 array([0, 0, 1, 0, 0, 0, 0, 0]),
 array([0, 0, 1, 0, 0, 0, 0, 0]),
 array([1, 0, 

1.0