In [3]:
import numpy as np 
np.random.seed(42)

features = [np.random.rand(8,10) for i in range(10000)]

theta = np.random.rand(10, 1).reshape(1,-1)
np.save('theta.npy', theta)
np.save('features1.npy', features)

In [19]:
ut_list = [(features[i] @ theta.T).reshape(1,-1) for i in range(10000)]

In [23]:
def prob(vj_list):
    sum = np.sum(np.exp(vj_list)) 
    return [np.exp(vj_list[i]) / sum for i in range(len(vj_list))]  

In [30]:
prob_list = [prob(ut_list[i])[0] for i in range(10000)]
prob_list 

[array([0.1646212 , 0.11119652, 0.06587548, 0.08320822, 0.06726448,
        0.23184954, 0.1850142 , 0.09097036]),
 array([0.14026964, 0.09995166, 0.05432612, 0.20859084, 0.19936384,
        0.09816753, 0.08014949, 0.11918088]),
 array([0.12611194, 0.06033275, 0.15217126, 0.27737233, 0.0302754 ,
        0.14598882, 0.12360859, 0.08413891]),
 array([0.33296132, 0.09536242, 0.10116545, 0.27007581, 0.05138151,
        0.04658646, 0.07162545, 0.03084158]),
 array([0.14531794, 0.05853599, 0.09100682, 0.11682438, 0.12565669,
        0.04283175, 0.14353198, 0.27629445]),
 array([0.09882159, 0.19938251, 0.09752474, 0.07686227, 0.19204162,
        0.0656689 , 0.17226236, 0.097436  ]),
 array([0.11848566, 0.09263704, 0.14627591, 0.07686062, 0.14700906,
        0.26079271, 0.08355027, 0.07438872]),
 array([0.09364022, 0.19155792, 0.0827281 , 0.08357545, 0.07719036,
        0.1793489 , 0.08873894, 0.2032201 ]),
 array([0.10077659, 0.07470375, 0.07169322, 0.12281065, 0.07719437,
        0.08932728, 

In [31]:
prob_list[0]

array([0.1646212 , 0.11119652, 0.06587548, 0.08320822, 0.06726448,
       0.23184954, 0.1850142 , 0.09097036])

In [60]:
import random
def get_purchase(problist):
    returnlist = [0 for i in range(len(problist))]
    indexchoose = random.choices([i for i in range(len(problist))], weights = problist)[0]
    returnlist[indexchoose] = 1
    return np.array(returnlist)


In [61]:
purchase_list = []
for i in range(10000):
    purchase_list.append(get_purchase(prob_list[i]))

In [65]:
prob_list
np.save('prob_list.npy', prob_list)

In [62]:
purchase_list

[array([1, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 1]),
 array([0, 0, 0, 1, 0, 0, 0, 0]),
 array([1, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 1, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 1, 0]),
 array([0, 0, 0, 0, 0, 1, 0, 0]),
 array([0, 0, 0, 1, 0, 0, 0, 0]),
 array([0, 0, 0, 1, 0, 0, 0, 0]),
 array([1, 0, 0, 0, 0, 0, 0, 0]),
 array([1, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 1, 0, 0, 0]),
 array([0, 1, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 1, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 1, 0, 0]),
 array([0, 0, 0, 1, 0, 0, 0, 0]),
 array([0, 0, 0, 1, 0, 0, 0, 0]),
 array([0, 1, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 1, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 1, 0, 0, 0, 0]),
 array([0, 1, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 1, 0, 0]),
 array([0, 1, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 1, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 1]),
 array([0, 0, 0, 0, 0, 0, 0, 1]),
 array([0, 0, 0, 0, 0, 0, 1, 0]),
 array([0, 0, 0, 0, 0, 0, 1, 0]),
 array([0, 0, 0, 0, 1, 0, 0, 0]),
 array([0, 0, 

In [64]:
np.save('purchase.npy', purchase_list)